import = ["~/.config/alacritty/dracula.toml"]

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"

[window]
opacity = 1
decorations = "Buttonless"

[window.padding]
x = 0
y = 0

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[selection]
save_to_clipboard = false
