# Environment
env TERM=xterm-256color

# Shell
shell /bin/zsh

# Wayland/X11
linux_display_server auto

# Window appearance
hide_window_decorations no
window_padding_width 5
background_opacity 1.0
dynamic_background_opacity no
confirm_os_window_close 0

# Scrolling
scrollback_lines 10000
wheel_scroll_multiplier 3.0

# Fonts
font_family      JetBrainsMono Nerd Font
# bold_font        JetBrainsMono Nerd Font Bold
bold_font        auto
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 9.0
font_hinting full
disable_ligatures always

modify_font cell_height 105%

# Selection / clipboard
copy_on_select clipboard
strip_trailing_spaces never
clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
select_by_word_characters ,│`|:"' ()[]{}<>

# Cursor
cursor_shape underline
cursor_shape_unfocused hollow
cursor_underline_thickness 0.15
shell_integration no-cursor

# Mouse
mouse_hide_wait -1.0
mouse_map middle release ungrabbed paste_from_selection

# Keyboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+l clear_terminal scroll active
map shift+page_up scroll_page_up
map shift+page_down scroll_page_down
map shift+home scroll_home
map shift+end scroll_end
map ctrl+shift+/ search_scrollback
map ctrl+shift+b no_op
map ctrl+0 change_font_size all 0
map shift+enter send_text normal,application \x1b\x0d

# Theme import
include ~/.config/kitty/dracula.conf
